user  nobody;
worker_processes  2;

events {
    worker_connections  1024;
}


http {
    server_tokens off;

    fastcgi_hide_header X-Powered-By;
    fastcgi_hide_header X-Pingback;
    fastcgi_hide_header Link;
    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-XSS-Protection "1; mode=block";
    proxy_hide_header X-Powered-By;
    proxy_hide_header X-Pingback;
    proxy_hide_header Link;
    disable_symlinks on;
    client_max_body_size 20M;


    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for" '
                      '"upstream=$upstream_addr" "up_status=$upstream_status" "urt=$upstream_response_time" ';

    access_log  /logs/nginx/access.log  main;
    error_log   /logs/nginx/error.log;
    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   60;
    types_hash_max_size 2048;
    gzip        on;
    gzip_disable "MSIE[1-6].(?!.*SV1)";
    gzip_vary   on;
    gzip_min_length     1024;
    gzip_proxied        any;
    gzip_comp_level     5;
    gzip_buffers        16 8k;
    gzip_types text/css text/js text/plain text/json text/javascript application/json application/javascript application/x-font-truetype application/x-font-ttf application/xml font/eot font/otf image/svg+xml;

    default_type application/octet-stream;

    include /usr/local/nginx/conf/mime.types;
    include /usr/local/nginx/conf.d/*.conf;
  }

