# nginx 전역 설정

#user  nobody;
worker_processes  auto;
worker_rlimit_nofile 8192;
pid        logs/nginx.pid;

events {
    use epoll;
    worker_connections  8192;
    multi_accept on;
}

http {
    server_tokens off;
    disable_symlinks off;
    default_type  application/octet-stream;
    more_set_headers "Server: JWS";
    more_clear_headers 'X-Powered-By';

    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";

    log_format main '$remote_addr - $remote_user [$time_local] '
                    '$host '
                    '"$request" $status '
                    'upstream_status=$upstream_status '
                    '$body_bytes_sent '
                    '"$http_referer" "$http_user_agent" '
                    'rt=$request_time urt=$upstream_response_time';

    sendfile        on;
    keepalive_timeout  300;
    reset_timedout_connection on;

    gzip  on;
    open_file_cache max=10000 inactive=30s;
    open_file_cache_valid 60s;
    open_file_cache_errors on;
    #client_max_body_size 100M;

    include /usr/local/nginx/conf/mime.types;
    include /usr/local/nginx/conf.d/*.conf;
  }
