# /etc/logrotate.d/nginx 파일에 설정

/logs/nginx/test.co.kr/*.log
/logs/nginx/test1.co.kr/*.log
/logs/nginx/test2.co.kr/*.log
{
        daily
        dateext
        missingok
        rotate 7
        compress
        notifempty
        sharedscripts
        postrotate
                test -r /usr/local/nginx/logs/nginx.pid && kill -USR1 `cat /usr/local/nginx/logs/nginx.pid`
        endscript
}

