    # robots.txt만 1:1로 리다이렉트
        location = /robots.txt {
                return 301 https://test.jtbc.co.kr/robots.txt;
        }

    # 나머지 모든 요청은 메인 도메인으로 리다이렉트
        location / {
                return 301 https://test.jtbc.co.kr;
        }

   # return 할때 하위 도메인까지 매칭
     return 301 https://www.test.co.kr$request_uri;
